name: diff-so-fancy
title: Diff-so-fancy
summary: Good-lookin' diffs. Actually… nah… The best-lookin' diffs.
description: |
  diff-so-fancy strives to make your diffs human readable instead of machine
  readable. This helps improve code quality and helps you spot defects faster.
license: MIT

adopt-info: diff-so-fancy
confinement: strict
grade: stable
base: core24

apps:
  diff-so-fancy:
    command: diff-so-fancy
    environment:
      LC_ALL: "C.UTF-8"
      PERL5LIB:  "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl-base/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl/5.38/:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.38/"


parts:
  diff-so-fancy:
    plugin: dump
    source: https://github.com/so-fancy/diff-so-fancy.git
    build-packages:
      - libapp-fatpacker-perl
    stage-packages:
      - git
      - perl
    override-build: |
      # build the latest tagged release
      latest_tag=$(git tag --list | grep '^v' | tail -1)
      git checkout ${latest_tag?}
      craftctl set version=$(git describe --tags)
      # we now need to build the fatpack version as it's no longer committed
      perl third_party/build_fatpack/build.pl
      cp -v /tmp/diff-so-fancy $SNAPCRAFT_PART_INSTALL/
